# Generated by Django 2.0 on 2018-11-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_auto_20181104_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cobertura', models.ManyToManyField(to='teste.Cobertura')),
            ],
        ),
    ]
