# Generated by Django 2.1.3 on 2018-11-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
